//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HammerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hammer
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public double Cost { get; set; }
        public double ListPrice { get; set; }
        public int Quantity { get; set; }
    }
}
